name: BuildTC

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install VS Build Tools
        run: choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools" -y

      - name: Install CMake
        run: choco install cmake -y

      - name: Configure
        run: cmake -B build -S . -A x64 -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: TC-Build
          path: |
            build/bin/Release/worldserver.exe
            build/bin/Release/authserver.exe
            build/bin/Release/
